name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: AWS Build Stage
        run: echo "Simulating AWS CodeBuild"

      - name: AWS Deploy Stage
        run: echo "Simulating AWS CodeDeploy"

      - name: AWS Monitoring Stage
        run: echo "Simulating AWS CloudWatch monitoring"
